title: S.W.O.R.D. Team Blog
tagline: "تیم هوافضای دانشجویی"
description: "پروژه‌ها، اعضا و مستندات ما"
url: "https://SWORDTEAMUUT.github.io"  
baseurl: "/repo-name"

remote_theme: cotes2020/jekyll-theme-chirpy

lang: fa
timezone: Asia/Tehran

theme_mode: dark

markdown: kramdown
highlighter: rouge

paginate: 5

nav:
  - name: Home
    url: /
  - name: درباره ما
    url: /about/
  - name: پروژه‌ها
    url: /projects/
  - name: تماس با ما
    url: /contact/

footer:
  since: 2025
  license: MIT License


